/**
 * Compile the curated KB (.md files under sources/tr1 and sources/tr2) into a
 * single bundled TS module, lib/kb-content.generated.ts.
 *
 * Why generate instead of reading files at runtime: on Vercel's serverless
 * runtime the sources/ folder isn't reliably traced into the function bundle.
 * A generated module is always bundled with the code and needs no fs access.
 *
 *   npm run build:kb     # regenerate manually
 * Also runs automatically on `prebuild` (before every `next build`), so a
 * deploy always reflects the current .md files.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, resolve, relative } from "node:path";

const ROOT = resolve("sources");
const DIRS = ["tr1", "tr2"]; // tr2 is walked recursively, so phase2 is included

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith(".md")) out.push(full);
  }
  return out;
}

/** Ref label from filename: TR1-001_markets.md → TR1-001, TR2-P2-003_x.md → TR2-P2-003. */
function refFromName(file: string): string {
  const base = file.split(/[\\/]/).pop() ?? file;
  const m = base.match(/^([A-Za-z0-9-]+?)(?:_|\.md)/);
  return m ? m[1] : base.replace(/\.md$/, "");
}

/** First H1 as the title, else the ref. */
function titleOf(content: string, fallback: string): string {
  const m = content.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : fallback;
}

const files: string[] = [];
for (const d of DIRS) {
  const p = join(ROOT, d);
  try {
    if (statSync(p).isDirectory()) files.push(...walk(p));
  } catch {
    // dir missing — skip
  }
}

// TR1 (ground truth) first, then TR2, each alphabetical by path.
files.sort((a, b) => {
  const ra = relative(ROOT, a).replace(/\\/g, "/");
  const rb = relative(ROOT, b).replace(/\\/g, "/");
  const ta = ra.startsWith("tr1/") ? 0 : 1;
  const tb = rb.startsWith("tr1/") ? 0 : 1;
  if (ta !== tb) return ta - tb;
  return ra.localeCompare(rb);
});

const blocks = files.map((f) => {
  const content = readFileSync(f, "utf8").trim();
  const ref = refFromName(f);
  const title = titleOf(content, ref);
  return `===== ${ref} · ${title} =====\n\n${content}`;
});

const KB = blocks.join("\n\n\n");
const approxTokens = Math.round(KB.length / 4);

const header =
  "// AUTO-GENERATED by scripts/build-kb.ts — do not edit by hand.\n" +
  "// Regenerate: npm run build:kb (also runs automatically on prebuild).\n" +
  `// Source: ${files.length} files under sources/tr1 and sources/tr2.\n\n`;

const out =
  header +
  `export const KB_CONTENT = ${JSON.stringify(KB)};\n` +
  `export const KB_FILE_COUNT = ${files.length};\n` +
  `export const KB_APPROX_TOKENS = ${approxTokens};\n`;

writeFileSync(resolve("lib/kb-content.generated.ts"), out, "utf8");
console.log(`build-kb: wrote lib/kb-content.generated.ts (${files.length} files, ~${approxTokens} tokens)`);
